# Generated by Django 4.1.3 on 2022-12-10 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0004_post_category_alter_category_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
