# Generated by Django 4.1.3 on 2022-12-10 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0006_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
